version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: example_dev_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=example_dev
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - go-http-gorm-example

  app:
    build: .
    container_name: example_dev_go_http_gorm
    environment:
      - CONFIG_FILE=config.dev.yaml
    ports:
      - 8080:8080
    networks:
      - go-http-gorm-example

networks:
  go-http-gorm-example:
    driver: bridge
