// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/books/types/data_provider.go
//
// Generated by this command:
//
//	mockgen --destination ./pkg/books/testutil/mock_data_provider.go --source ./pkg/books/types/data_provider.go --package testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	types "github.com/nkitlabs/go-http-gorm-example/pkg/books/types"
	db "github.com/nkitlabs/go-http-gorm-example/pkg/db"
	gomock "go.uber.org/mock/gomock"
)

// MockDataProvider is a mock of DataProvider interface.
type MockDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDataProviderMockRecorder
}

// MockDataProviderMockRecorder is the mock recorder for MockDataProvider.
type MockDataProviderMockRecorder struct {
	mock *MockDataProvider
}

// NewMockDataProvider creates a new mock instance.
func NewMockDataProvider(ctrl *gomock.Controller) *MockDataProvider {
	mock := &MockDataProvider{ctrl: ctrl}
	mock.recorder = &MockDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProvider) EXPECT() *MockDataProviderMockRecorder {
	return m.recorder
}

// CreateBook mocks base method.
func (m *MockDataProvider) CreateBook(book types.Book) (types.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", book)
	ret0, _ := ret[0].(types.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockDataProviderMockRecorder) CreateBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockDataProvider)(nil).CreateBook), book)
}

// DeleteBook mocks base method.
func (m *MockDataProvider) DeleteBook(book *types.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockDataProviderMockRecorder) DeleteBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockDataProvider)(nil).DeleteBook), book)
}

// GetBook mocks base method.
func (m *MockDataProvider) GetBook(id int) (*types.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBook", id)
	ret0, _ := ret[0].(*types.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBook indicates an expected call of GetBook.
func (mr *MockDataProviderMockRecorder) GetBook(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBook", reflect.TypeOf((*MockDataProvider)(nil).GetBook), id)
}

// GetBooks mocks base method.
func (m *MockDataProvider) GetBooks(page, limit int, sortType db.SortType) (*db.Pagination, []types.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks", page, limit, sortType)
	ret0, _ := ret[0].(*db.Pagination)
	ret1, _ := ret[1].([]types.Book)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockDataProviderMockRecorder) GetBooks(page, limit, sortType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockDataProvider)(nil).GetBooks), page, limit, sortType)
}

// UpdateBook mocks base method.
func (m *MockDataProvider) UpdateBook(book *types.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockDataProviderMockRecorder) UpdateBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockDataProvider)(nil).UpdateBook), book)
}
